name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Show Node & npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: 'Deploy to Azure Static Web Apps'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # set in repo secrets
          repo_token: ${{ secrets.GITHUB_TOKEN }} # optional, used for PR comments
          action: 'upload'
          app_location: '/' # app repo root
          api_location: ''   # no functions API in this repo; set if you have one
          output_location: 'dist' # Vite build output

